name: 发布发行版

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write   # 允许对仓库内容进行写操作（包括标签）
  issues: write     # 如果使用 label 相关操作，确保给与 Issues 写权限
  pull-requests: write  # 确保可以创建和修改 PR

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 检出代码
        uses: actions/checkout@v3

      - name: 🛠️ 安装 Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 📦 安装依赖 & 构建项目
        run: |
          bun install
          bun run build

      - name: 🚀 运行 release-please，生成版本和 Release Notes
        id: release
        uses: googleapis/release-please-action@v4
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: 📦 打包为 tarball
        if: ${{ steps.release.outputs.release_created }}
        run: |
          bun pm pack

      - name: 🗃 上传打包文件到 GitHub Release
        if: ${{ steps.release.outputs.release_created }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release.outputs.tag_name }}
          name: ${{ steps.release.outputs.tag_name }}
          body: ${{ steps.release.outputs.release_notes }}
          files: "*.tgz"
